<?php
/*
{
    Module: photocrati-comments,
    Depends: { photocrati-ajax, photocrati-datamapper }
}
*/
class M_Photocrati_Comments extends C_Base_Module
{
    protected $_interrupt_comment_post_redirection = FALSE;

    // not all parts of WP should 'see' our comments
    public static $_filter_comments = TRUE;

    function define($context=FALSE)
    {
        parent::define(
            'photocrati-comments',
            'Comments',
            'AJAX operations for retrieving and creating comments on arbitrary items',
            '0.9',
            'http://www.photocrati.com',
            'Photocrati Media',
            'http://www.photocrati.com',
            $context
        );
    }

    function get_type_list()
    {
        return array(
            'A_Comment_Factory' => 'adapter.comment_factory.php',
            'A_Comment_Controller' => 'adapter.comment_controller.php',
            'C_Comment_Mapper' => 'class.comment_mapper.php',
            'C_Comment_Container' => 'class.comment_container.php'
        );
    }

    function _register_hooks()
    {
        add_action('init',                  array(&$this, 'register_post_type'));
        add_action('pre_comment_on_post',   array(&$this, 'pre_comment_on_post'));

        add_filter('comment_post_redirect', array(&$this, 'comment_post_redirect'), 10, 2);
		add_filter('post_type_link',		array(&$this, 'set_custom_post_link'), NULL, 2);
		add_filter('get_edit_post_link',    array(&$this, 'set_custom_post_link'), NULL, 2);
		if (!is_admin())
            add_filter('the_comments', array(&$this, 'the_comments'));
    }

	function set_custom_post_link($post_link, $post)
	{
		if (is_int($post)) $post = get_post($post);

		if ($post->post_type == 'photocrati-comments') {
			if (preg_match("/^http(s)?/", $post->post_excerpt)) {
				$post_link = $post->post_excerpt;
			}
			else {
				$image_id = intval(str_replace('nextgen-comment-link-image-', '', $post->post_name));
				if (($image = C_Image_Mapper::get_instance()->find($image_id))) {
					$post_link = wp_nonce_url('admin.php?page=nggallery-manage-gallery&mode=edit&gid='.$image->galleryid);
				}
			}
		}

		return $post_link;
	}

    function _register_adapters()
    {
        $this->get_registry()->add_adapter('I_Component_Factory', 'A_Comment_Factory');
        if (!is_admin())
            $this->get_registry()->add_adapter('I_Ajax_Controller', 'A_Comment_Controller');
    }

    function _register_utilities()
    {
        $this->get_registry()->add_utility('I_Comment_Mapper', 'C_Comment_Mapper');
    }

    function register_post_type()
    {
        register_post_type(
            'photocrati-comments',
            array(
                'labels' => array(
                    'name' => __('Comments'),
                    'singular_name' => __('Comment')
                ),
                'supports' => array(
                    'comments' => TRUE
                )
            )
        );
    }

    function pre_comment_on_post($post_id)
    {
        $post = get_post($post_id);
        if ($post->post_type == 'photocrati-comments' && !defined('DOING_AJAX' ))
        {
            // start a new output buffer just in case any plugins or themes throw any warnings, errors, or any other
            // unwanted texts from forcing themselves into our json response
            ob_start();
            $this->_interrupt_comment_post_redirection = TRUE;
            define('DOING_AJAX', TRUE);
        }
    }

    /**
     * The last action wp-comments-post.php before redirecting is to call the set_comment_post_redirect filter. To
     * prevent the WP 302 HTTP response we output our own json here and end execution. This should ONLY be done if
     * the pre_comment_on_post action (see above) has determined the comment belongs to one of our wrapper posts!
     *
     * @param $location
     * @throws E_Clean_Exit
     */
    function comment_post_redirect($location, $comment)
    {
        if ($this->_interrupt_comment_post_redirection)
        {
            // use this to track which comments we created
            add_comment_meta($comment->comment_ID, 'generated_by', 'photocrati-comments');

            if (isset($_REQUEST['nextgen_generated_comment']) && $_REQUEST['nextgen_generated_comment'] == 'true')
            {
                while (ob_get_level() > 0 ) {
                    ob_end_clean();
                }
                echo json_encode(array('success' => TRUE));
                throw new E_Clean_Exit();
            }
        }

        return $location;
    }

    /**
     * Applies a filter to recent comments that prevents comments generated by this module from appearing in
     * the "Recent Comments" widget provided by Wordpress
     *
     * @param array $comments
     * @return array $comments
     */
    function the_comments($comments = array())
    {
        // Unfortunately Wordpress' has poor ability to filter comments based on their metadata when calling
        // get_comments(). Because of this we must filter comments we have generated *after* allowing them to
        // be retrieved.
        if (self::$_filter_comments)
        {
            foreach ($comments as $ndx => $comment) {
                $meta = get_comment_meta($comment->comment_ID);
                if (!empty($meta['generated_by']) && $meta['generated_by'][0] == 'photocrati-comments')
                    unset($comments[$ndx]);
            }
        }

        return $comments;
    }
}

new M_Photocrati_Comments;
