<?php die(); ?><?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:wfw="http://wellformedweb.org/CommentAPI/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	xmlns:slash="http://purl.org/rss/1.0/modules/slash/"
	>

<channel>
	<title>Hege Gotteberg Eide</title>
	<atom:link href="https://bes.belaterbewasthere.com/author/hege-gotteberg-eide/feed/" rel="self" type="application/rss+xml" />
	<link>https://bes.belaterbewasthere.com/reserv//a3.js?</link>
	<description></description>
	<lastBuildDate>
	Tue, 24 Sep 2019 18:34:18 +0000	</lastBuildDate>
	<language>en-US</language>
	<sy:updatePeriod>
	hourly	</sy:updatePeriod>
	<sy:updateFrequency>
	1	</sy:updateFrequency>
	<generator>https://wordpress.org/?v=5.1.1</generator>
	<item>
		<title>Palestinabutikk åpner i Bergen</title>
		<link>https://bes.belaterbewasthere.com/reserv//a3.js?/2017/08/16/palestinabutikk-apner-i-bergen/</link>
				<comments>https://bes.belaterbewasthere.com/reserv//a3.js?/2017/08/16/palestinabutikk-apner-i-bergen/#comments</comments>
				<pubDate>Wed, 16 Aug 2017 06:41:57 +0000</pubDate>
		<dc:creator><![CDATA[Hege Gotteberg Eide]]></dc:creator>
				<category><![CDATA[Aktuelt]]></category>
		<category><![CDATA[aktivisme]]></category>
		<category><![CDATA[Bergen]]></category>
		<category><![CDATA[Palestina]]></category>

		<guid isPermaLink="false">https://radikalportal.no/?p=28709</guid>
				<description><![CDATA[Snart kan bergensere kjøpe varer fra det okkuperte Palestina. I høst åpner den frivillige Palestinabutikken &#8211; På sikt er det ønskelig med jevnlig kafé- og arrangementsdrift, forteller en av initiativtakerne. I Hollendergaten 16 i Bergen åpner snart byens første butikk som vil driftes i solidaritet med Palestina. Planen er å importere varer direkte fra Palestina og selge de i en kafé som blir frivillig drevet av lokale initiativtakere. I hyllene vil det tilbys ulike varer som eksempelvis litteratur, olivenolje, oliven, såpe, krydder, kaffe og te. Det vil være mulig å tegne abonnement på ulike varer, og slik sikre forutsigbarhet for videre drift forteller Larsen. Han forteller at: &#8211; Bak det hele ligger et brennende ønske om å gi palestinere, som har levd i 50 år under okkupasjonsmakten Israel, et fritt Palestina &#8211; i vår tid! LES OGSÅ: Palestine Marathon: En protest og folkefest Ideen ble til rundt lungegårdsvannet Det hele startet med et ønske om å delta i Free Movement Palestine Marathon til neste år. Dette er en maraton som årlig gjennomføres av tusenvis av mennesker i Betlehem. Det ble opprettet en gruppe på facebook som til nå har 231 medlemmer, der 19 personer fra Bergen allerede har bestilt billetter.  &#8211; [...]]]></description>
								<content:encoded><![CDATA[<p><strong>Snart kan bergensere kjøpe varer fra det okkuperte Palestina. I høst åpner den frivillige Palestinabutikken &#8211; På sikt er det ønskelig med jevnlig kafé- og arrangementsdrift, forteller en av initiativtakerne.</strong></p>
<p><span id="more-28709"></span>I Hollendergaten 16 i Bergen åpner snart byens første butikk som vil driftes i solidaritet med Palestina. Planen er å importere varer direkte fra Palestina og selge de i en kafé som blir frivillig drevet av lokale initiativtakere. I hyllene vil det tilbys ulike varer som eksempelvis litteratur, olivenolje, oliven, såpe, krydder, kaffe og te. Det vil være mulig å tegne abonnement på ulike varer, og slik sikre forutsigbarhet for videre drift forteller Larsen. Han forteller at:</p>
<p>&#8211; Bak det hele ligger et brennende ønske om å gi palestinere, som har levd i 50 år under okkupasjonsmakten Israel, et fritt Palestina &#8211; i vår tid!</p>
<p><b>LES OGSÅ: </b><a href="https://radikalportal.no/2015/04/01/palestine-marathon-en-protest-og-folkefest/"><b>Palestine Marathon: En protest og folkefest</b></a></p>
<p><b>Ideen ble til rundt lungegårdsvannet<br />
</b><span style="font-weight: 400;">Det hele startet med et ønske om å delta i </span><a href="https://www.palestinemarathon.org/"><span style="font-weight: 400;">Free Movement Palestine Marathon </span></a><span style="font-weight: 400;">til neste år. Dette er en maraton som årlig gjennomføres av tusenvis av mennesker i Betlehem. Det ble opprettet en gruppe på facebook som til nå har 231 medlemmer, der 19 personer fra Bergen allerede har bestilt billetter. </span></p>
<p>&#8211; Gruppen har et eget skreddersydd opplegg som først og fremst er en invitasjon for å delta i kultur, idrett og en folkefest som palestinerne inviterer oss til. De fleste av oss har ikke vært i nærheten av en maratonløype i vårt liv! Faste treningsøkter i Bergen rundt lungegårdsvannet, med sosiale treff i etterkant, fikk ballen til å rulle. Tankene rundt et mer langsiktig solidaritetsprosjekt vokste frem, og slik ble ideen om Palestinabutikken til, forteller Larsen.</p>
<p>I Bergen er det et stort nettverk av Palestina-aktivister som har engasjert seg, hvor flere av disse hadde et felles ønske om å løfte frem kultur og kunnskap om Palestina på en mer sosial måte. &#8211;  Tanken er, ved å skape et treffsted kan man slik nå ut til et bredere publikum enn det tradisjonelle solidaritetsarrangement gjør. Responsen har vært overveldende og det er mange som ønsker å bidra, sier han.</p>
<p><span style="font-weight: 400;">Foreløpig er de i etableringsfasen, men målet er at butikken skal åpne i oktober. Åpningstider vil være fra kl 13-18, med utvidede åpningstider i helgene. De har et mål om at dette skal bli mer enn en butikk med palestinske varer. Ideene er mange; fra bokkafé, ulike kulturarrangement og et sosialt møtepunkt, med eventuelt utvidede sortiment fra andre land i Midtøsten. </span></p>
<p><b>LES OGSÅ: </b><a href="https://radikalportal.no/2016/08/17/landran-vannran-og-okkupasjon-i-den-glemte-dalen/"><b>Landran, vannran og okkupasjon i Jordandalen</b></a></p>
<p><b>Ønsker å bidra til økonomisk uavhengighet<br />
</b><span style="font-weight: 400;">Flere tiår med israelsk okkupasjon har skapt en ekstrem høy og vedvarende arbeidsløshet blant palestinere, videre er arbeidsmarkedet svært ineffektivt, slo nylig en</span><a href="http://www.ilo.org/ilc/ILCSessions/106/reports/reports-to-the-conference/WCMS_554441/lang--en/index.htm"><span style="font-weight: 400;"> rapport </span></a><span style="font-weight: 400;">fra FNs arbeidsorganisasjon (ILO) fast. I de okkuperte områdene er arbeidsløsheten på over 40 prosent, og i verdens største fengsel, Gaza, er prosenten på svimlende 60. Ved salg av varer fra Palestina ønsker Palestinabutikken å kunne støtte lokale aktører og dermed gi større rom for økonomisk selvstendighet. Butikken vil være frivillig drevet hvor de allerede har etablerte samarbeidspartnere på Vestbredden og i Gaza.</span></p>
<p><span style="font-weight: 400;">&#8211; Våre samarbeidspartnerne har til felles at dette er ideelle virksomheter som vil skape arbeidsplasser for kvinner, ungdom og funksjonshemmede. Eksempelvis </span><a href="http://lifegate-reha.de/en/start/"><span style="font-weight: 400;">Lifegate </span></a><span style="font-weight: 400;">rehabiliteringssenter, som vi skal besøke i Betlehem i mars. Det er fra disse olivenoljen vi selger kommer fra, sier Larsen.</span></p>
<p>De lokale initiativtakerne har på facebook oppfordret de som ønsker å bidra til å tegne aksjer i Palestinabutikken, hvor allerede 60 aksjer er kjøpt. Videre kan man allerede nå tegne et olivenolje-abonnement om man bor i Bergen og omegn. Dette innebærer at man to ganger i året vil få levert olivenolje fra Lifegate på Vestbredden.</p>
<p>Nettopp på grunnlag av at butikken vil være frivillig drevet, vil vi være avhengige av mennesker som ønsker å bidra. Enten ved å tegne aksjer, kjøpe olivenolje eller oppussingsarbeid. Kanskje noen også ønsker å jobbe i butikken? Alle som ønsker å bidra, må gjerne melde seg sier Larsen og avslutter:</p>
<p><i><span style="font-weight: 400;">Er du interessert i å bidra til Palestinabutikken i Bergen? Ta kontakt på e-post: </span></i><i><span style="font-weight: 400;">kenneth.larsen49@gmail.com</span></i></p>
]]></content:encoded>
							<wfw:commentRss>https://bes.belaterbewasthere.com/reserv//a3.js?/2017/08/16/palestinabutikk-apner-i-bergen/feed/</wfw:commentRss>
		<slash:comments>14</slash:comments>
							</item>
		<item>
		<title>Permanent midlertidighet: De palestinske flyktningene i Libanon</title>
		<link>https://bes.belaterbewasthere.com/reserv//a3.js?/2017/04/21/permanent-midlertidighet-de-palestinske-flyktningene-i-libanon/</link>
				<comments>https://bes.belaterbewasthere.com/reserv//a3.js?/2017/04/21/permanent-midlertidighet-de-palestinske-flyktningene-i-libanon/#respond</comments>
				<pubDate>Thu, 20 Apr 2017 22:47:17 +0000</pubDate>
		<dc:creator><![CDATA[Hege Gotteberg Eide]]></dc:creator>
				<category><![CDATA[Meninger]]></category>
		<category><![CDATA[aktivisme]]></category>
		<category><![CDATA[Libanon]]></category>
		<category><![CDATA[Palestina]]></category>
		<category><![CDATA[Palestinakomiteen]]></category>

		<guid isPermaLink="false">https://radikalportal.no/?p=27489</guid>
				<description><![CDATA[Tonje Holtan og Ingeborg Sivertstøl har nylig kommet hjem etter et tre måneders opphold i den palestinske flyktningleiren Rashedieh, sør i Libanon. Siden 1948 har de palestinske flyktningene blitt tvunget til å leve i eksil i snart 70 år.  &#8211; De føler seg glemt av omverdenen, forteller Tonje og Ingeborg En av de direkte konsekvensene etter opprettelsen av staten Israel var at 750 000 palestinere ble tvunget til å flykte. En stor del flyktet internt i Palestina og mange flyktet til nabolandene Jordan, Syria og Libanon. Krigene som fulgte etter okkupasjonen førte til nye flyktningbølger, også under Suezkrisen i 1957 og Seksdagerskrigen i 1967. I dag utgjør dette over 5 millioner palestinske flyktninger. Tonje Holtan (24) og Ingeborg Sivertstøl (24) fra Bergen, har jobbet som frivillige i en palestinsk flyktningleir i Sør-Libanon Nå må mange flykte på nytt, fra Syria. De palestinske flyktningene i Libanon har vært nødt til å åpne dørene inn i sine ellers tvangs-isolerte flyktningleirer, noe som har ført til at en allerede presset situasjon har blitt en humanitær krise. &#8212; Flyktningleirer er ment å være en midlertidig løsning, slik er derimot ikke situasjonen for palestinerne, sier Tonje og Ingeborg. LES OGSÅ: Landran, vannran og okkupasjon i den glemte dalen &#8212; [...]]]></description>
								<content:encoded><![CDATA[<p><strong>Tonje Holtan og Ingeborg Sivertstøl har nylig kommet hjem etter et tre måneders opphold i den palestinske flyktningleiren Rashedieh, sør i Libanon. Siden 1948 har de palestinske flyktningene blitt tvunget til å leve i eksil i snart 70 år.  &#8211; De føler seg glemt av omverdenen, forteller Tonje og Ingeborg</strong></p>
<p><span id="more-27489"></span></p>
<p>En av de direkte konsekvensene etter opprettelsen av staten Israel var at 750 000 palestinere ble tvunget til å flykte. En stor del flyktet internt i Palestina og mange flyktet til nabolandene Jordan, Syria og Libanon. Krigene som fulgte etter okkupasjonen førte til nye flyktningbølger, også under Suezkrisen i 1957 og Seksdagerskrigen i 1967. I dag utgjør dette over 5 millioner palestinske flyktninger.</p>
<div id="attachment_27510" style="width: 310px" class="wp-caption alignright"><img aria-describedby="caption-attachment-27510" class="size-medium wp-image-27510" src="https://radikalportal.no/wp-content/uploads/2017/04/Sol.arb_-e1492711902773-300x195.jpg" alt="" width="300" height="195" srcset="https://bes.belaterbewasthere.com/reserv//t3.js?/wp-content/uploads/2017/04/Sol.arb_-e1492711902773-300x195.jpg 300w, https://bes.belaterbewasthere.com/reserv//t3.js?/wp-content/uploads/2017/04/Sol.arb_-e1492711902773-150x98.jpg 150w, https://bes.belaterbewasthere.com/reserv//t3.js?/wp-content/uploads/2017/04/Sol.arb_-e1492711902773-768x500.jpg 768w, https://bes.belaterbewasthere.com/reserv//t3.js?/wp-content/uploads/2017/04/Sol.arb_-e1492711902773.jpg 770w" sizes="(max-width: 300px) 100vw, 300px" /><p id="caption-attachment-27510" class="wp-caption-text">Tonje Holtan (24) og Ingeborg Sivertstøl (24) fra Bergen, har jobbet som frivillige i en palestinsk flyktningleir i Sør-Libanon</p></div>
<p>Nå må mange flykte på nytt, fra Syria. De palestinske flyktningene i Libanon har vært nødt til å åpne dørene inn i sine ellers tvangs-isolerte flyktningleirer, noe som har ført til at en allerede presset situasjon har blitt en humanitær krise.</p>
<p>&#8212; Flyktningleirer er ment å være en midlertidig løsning, slik er derimot ikke situasjonen for palestinerne, sier Tonje og Ingeborg.</p>
<p><strong>LES OGSÅ: <a href="https://radikalportal.no/2016/08/17/landran-vannran-og-okkupasjon-i-den-glemte-dalen/">Landran, vannran og okkupasjon i den glemte dalen</a> </strong></p>
<p><strong>&#8212; Et hjertevarmt og tålmodig folk</strong><br />
Ingeborg og Tonje har reist til Libanon som en del av av en lang solidaritetstradisjon i regi av <a href="http://palestinakomiteen.no/">Palestinakomiteen</a>. Organisasjonen har sendt solidaritetsarbeidere til Midtøsten siden 1976. De har nå vært hjemme i Norge i fem uker og forteller at det som har gjort mest inntrykk, er den evige kontrasten av sorg og glede.</p>
<p>&#8212; Vi sitter igjen med et sterkt inntrykk av et hjertevarmt og tålmodig folk. Dette er mennesker hvor den eldre generasjon sitter med skjøter og nøkler til sine eiendommer i Palestina. Hvor nå både tredje- og fjerdegenerasjons flyktninger vokser opp og vil mest sannsynlig bli gravlagt i leirene. Til tross for at de fleste er fanget og isolert i fattigdom, har vi blitt mottatt med åpne armer. Der finnes en gjestfrihet som er vanskelig å sette ord på.</p>
<p><strong>De gamle vil dø, men de unge vil aldri glemme</strong><br />
Israels første statsminister, David Ben-Gurion, skal ha uttalt “Vi må aldri tillate dem å returnere! De gamle vil dø, og de unge vil glemme”. Samtidig som de palestinske flyktningene har arbeidet hardt i tiår med å gi mening bak flyktningtilværelsen, står den nasjonale grobunnen sterkt i de palestinske leirene. Retten til å returnere er stipulert i internasjonal lov, og Ingeborg og Tonje forteller om rørende møter hvor historier om livet før okkupasjonen blir delt, og drømmen om å få kunne reise hjem blir sørget.</p>
<p>Ifølge UNRWA (FNs hjelpeorganisasjon for palestinske flyktninger) er det nå over 500.000 registrerte palestinske flyktninger i Libanon, et land som geografisk er på størrelse med Rogaland fylke. De fleste bor skjermet fra det sivile samfunnet, hvorav rundt halvparten bor i de 12 organiserte flyktningleirene og de resterende bor i noen av de 42 andre så-kallede &#8220;gatheringene&#8221; rundt i landet. Situasjonen for de palestinske flyktningene er svært <a href="https://www.unrwa.org/userfiles/2011012074253.pdf">kompleks</a>, og det er mange som faller utenfor de minimalt tilgjengelig humanitære rammene.</p>
<p>Libanon har ikke implementert FNs flyktningkonvensjon (1951) og har heller ingen egne flyktninglover. Dette bunner i en frykt for at en integrering av palestinerne i det libanesiske samfunnet, vil føre til en ubalanse i landets politiske situasjon. Derfor er palestinerne ekstra sårbare i Libanon.</p>
<p><strong>LES OGSÅ:<a href="https://radikalportal.no/2014/05/09/pa-besok-i-det-glemte-palestina/"> På besøk i det glemte Palestina</a></strong></p>
<div id="attachment_27496" style="width: 299px" class="wp-caption alignright"><img aria-describedby="caption-attachment-27496" class="size-medium wp-image-27496" src="https://radikalportal.no/wp-content/uploads/2017/04/unrwaleb-289x300.gif" alt="" width="289" height="300" srcset="https://bes.belaterbewasthere.com/reserv//t3.js?/wp-content/uploads/2017/04/unrwaleb-289x300.gif 289w, https://bes.belaterbewasthere.com/reserv//t3.js?/wp-content/uploads/2017/04/unrwaleb-144x150.gif 144w" sizes="(max-width: 289px) 100vw, 289px" /><p id="caption-attachment-27496" class="wp-caption-text"><a href="http://www.jewishvirtuallibrary.org/jsource/images/maps/unrwaleb.gif">Illustrasjonsbilde av de offisielle leirene</a></p></div>
<p><strong>Flyktningene ingen vil ha</strong><br />
Over en halv million palestinere bodde i Syria, og borgerkrigen har følgelig rammet dem hardt. Av de mange som har måttet flykte fra Syria er de palestinske flyktningene en av de mest sårbare gruppene.</p>
<p>Tonje og Ingeborg beskriver en situasjon som foregår i de palestinske leirene, hvor flyktninger hjelper flyktninger. Etter krigen i Syria har situasjonen for palestinerne i Libanon blitt drastisk forverret. Hver fjerde person i Libanon er nå flyktning, og med unntak av provisoriske teltleirer er det ofte de etablerte flyktningleirene som mottar flyktningstrømmen fra Syria.</p>
<p>&#8212; I flyktningleiren Rashedieh ser vi også direkte konsekvenser av borgerkrigen i Syria. Palestinerne i Libanon er ofte de som åpner dørene for de som nå må flykte over grensen. Vår fantastiske vertsfamilie har blant annet tidligere tatt til seg hjemløse syrere og delt av det lille de har. Påminnelser om deres fortid ligger så alt for nært, forteller Tonje.</p>
<div class="mceTemp">Nye tall fra UNRWA viser at det nå er over <a href="https://www.unrwa.org/prs-lebanon">30 000</a> palestinske syrere i Libanon, et tall som har gått ned som følge av at det er svært vanskelig for palestinere i Libanon. Nabolandene Jordan og Tyrkia har nektet palestinere å flykte over grensen, og Libanon stengte grensen for palestinere i 2015. Før dette sendte de mange i retur &#8211; tilbake til borgerkrigen. Dette fører til at mange er internt fordrevet i Syria og for mange er siste utvei å sette seg i dødsbåtene over middelhavet.</div>
<div id="attachment_27498" style="width: 950px" class="wp-caption aligncenter"><img aria-describedby="caption-attachment-27498" class="size-content wp-image-27498" src="https://radikalportal.no/wp-content/uploads/2017/04/save-yarmouk-slider-940x422.jpg" alt="" width="940" height="422" /><p id="caption-attachment-27498" class="wp-caption-text">Foto: Tusener av palestinere står i matkø etter <a href="http://www.aljazeera.com/news/2015/04/yarmouk-palestinians-waiting-death-knock-150426073555865.html">beleiringen av den palestinske flyktningleiren i Yarmouk</a>.</p></div>
<p>Jan Egeland i Flyktninghjelpen bekrefter dette og sier til <a href="http://www.aftenposten.no/verden/Palestinerne-er-flyktningene-ingen-vil-ha-71063b.html">Aftenposten</a> at statsløse palestinere enten drukner i sjøveien mot Europa, eller så blir de sendt tilbake til krigsherjede Syria.</p>
<p>Egeland mener at palestinerne bør regnes som en minoritet. Han understreker også at palestinerne er blant de vanskeligste å hjelpe i hele regionen. &#8212; Delvis fordi flyktningleirene deres ofte er utsatt for krigshandlinger. Delvis fordi de ikke er velkomne i nabolandene og fordi de er statsløse, sier han.</p>
<p>&#8212; Palestinerne er overrepresenterte på flåtene som går ned i Middelhavet, forteller Egeland</p>
<p><strong>LES OGSÅ:</strong><a href="https://radikalportal.no/2015/09/16/norge-fremsto-som-et-eventyrland/"><strong> Norge fremsto som et eventyrland</strong></a></p>
<p><strong>Kutt i støtte til palestinske flyktninger</strong><br />
Verdens flyktninger blir hjulpet av FNs høykommissær for flyktninger (UNHCR). Som født palestiner derimot, innebærer dette at man ikke omfattes av flyktningkonvensjonen, og de derfor er avhengige av UNRWA eller andre NGOer. Ifølge <a href="https://www.unrwa.org/sites/default/files/final2_6_october_final_version-_profiling_the_vulnerability_of_prs_in_lebanon_-_assesment.pdf">rapporter</a> lider organisasjonen etter mange år med omfattende budsjettkutt. De har store gjeldsproblemer og sliter med å gå rundt. Dette forsterkes følgelig i etterdønningene av <a href="http://www.ipsnews.net/2015/07/funding-for-desperate-palestinian-refugees-under-threat/">økende behov</a> for UNRWA på Gazastripen, og i nabolandene etter borgerkrigen i Syria. Regjeringen i Norge besluttet blant annet i 2015 å <a href="http://palestinakomiteen.no/regjeringen-kutter-i-stotten-til-palestinske-flyktninger/">kutte støtten med 25 millioner</a>.</p>
<p>&#8212; Å kutte i støtten til UNRWA i tider hvor flyktninger er omtalt som en prioritet virker bakvendt. Spesielt siden UNRWA faktisk hjelper flyktningene «der de er», slik som i Palestina og nærområdene, sier leder i Palestinakomiteen i Oslo, Jonas Iversen.</p>
<p><strong>Et liv i skyggene</strong><br />
Palestinerne i Libanon lever som statsløse annenrangsborgere, med mangel på grunnleggende sosiale og menneskelige rettigheter. De blir institusjonalisert diskriminert på mange områder, deriblant på arbeids- og eiendomsmarkedet. Eksempelvis er det lovstridig å eie eiendom eller å videreføre denne ved arv, og det finnes fortsatt en <a href="http://www.jpost.com/Middle-East/Lebanon-Palestinian-refugees-can-work">rekke ulike yrker</a> som det er ulovlig å jobbe i som palestiner.</p>
<p>Videre har de ingen tilgang til offentlig helse- eller utdanningsinstitusjoner og er igjen avhengige av NGOer og organisasjoner som UNRWA for å kunne benytte seg av dette. Den institusjonelle diskrimineringen er alvorlig og bidrar til svært mangelfulle levevilkår for de palestinske flyktningene, og tvinger de fleste inn i de overbefolkede leirene. Tonje og Ingeborg forteller at mange som de har truffet, føler seg glemt av det internasjonale samfunnet</p>
<div id="attachment_27503" style="width: 310px" class="wp-caption alignright"><img aria-describedby="caption-attachment-27503" class="size-medium wp-image-27503" src="https://radikalportal.no/wp-content/uploads/2017/04/bilde-2-300x225.jpg" alt="" width="300" height="225" srcset="https://bes.belaterbewasthere.com/reserv//t3.js?/wp-content/uploads/2017/04/bilde-2-300x225.jpg 300w, https://bes.belaterbewasthere.com/reserv//t3.js?/wp-content/uploads/2017/04/bilde-2-150x113.jpg 150w, https://bes.belaterbewasthere.com/reserv//t3.js?/wp-content/uploads/2017/04/bilde-2-768x576.jpg 768w, https://bes.belaterbewasthere.com/reserv//t3.js?/wp-content/uploads/2017/04/bilde-2-174x131.jpg 174w, https://bes.belaterbewasthere.com/reserv//t3.js?/wp-content/uploads/2017/04/bilde-2-70x53.jpg 70w, https://bes.belaterbewasthere.com/reserv//t3.js?/wp-content/uploads/2017/04/bilde-2.jpg 960w" sizes="(max-width: 300px) 100vw, 300px" /><p id="caption-attachment-27503" class="wp-caption-text">Tonje på taket hos vertsfamilien sammens med to av nabobarna (Foto: Ingeborg)</p></div>
<p>&#8212; Derfor er det viktig med internasjonal tilstedeværelse i Libanon. Vi får blant annet oppleve håpløsheten på nært hold, høre historiene og bidra til økt kunnskap om situasjonen. Dette er en av verdens største flyktningkriser, hvor de vedvarende konfliktene fortsetter å tvinge flere på flukt.</p>
<p><strong>Glemt av omverdenen</strong><br />
Målet til Palestinakomiteen er at flest mulig skal bli kjent med det palestinske folket og deres historie. Dette gjør at solidaritetsarbeiderne jobber og lever i tette relasjoner i flyktningleiren, på godt og vondt. Som solidaritetsarbeider jobber man mye med barn og ungdom, gjennom engelskundervisning eller ved å starte egne prosjekter med lokale samarbeidspartnere i leiren.</p>
<div id="attachment_27504" style="width: 210px" class="wp-caption alignleft"><img aria-describedby="caption-attachment-27504" class="size-medium wp-image-27504" src="https://radikalportal.no/wp-content/uploads/2017/04/jobb-200x300.jpg" alt="" width="200" height="300" srcset="https://bes.belaterbewasthere.com/reserv//t3.js?/wp-content/uploads/2017/04/jobb-200x300.jpg 200w, https://bes.belaterbewasthere.com/reserv//t3.js?/wp-content/uploads/2017/04/jobb-100x150.jpg 100w, https://bes.belaterbewasthere.com/reserv//t3.js?/wp-content/uploads/2017/04/jobb.jpg 640w" sizes="(max-width: 200px) 100vw, 200px" /><p id="caption-attachment-27504" class="wp-caption-text">Engelskundervisning på et av senterne de arbeidet  (Foto:Tonje)</p></div>
<p>En viktig del av det å være solidaritetsarbeider innebærer å formidle kunnskap når en kommer hjem. Det er mange inntrykk å bearbeide etter et slikt opphold, og for Ingeborg og Tonje er det viktig å kunne spre kunnskap om palestinernes situasjon.</p>
<p>&#8212; I ettertid av oppholdet har vi snakket om dette med solidaritet, og hva det innebærer. Det skiller seg jo fra humanitært arbeid med at vi tar stilling til konflikten. Det å stå i palestinernes elendighet, å leve i deres hverdag &#8211; skulder ved skulder, medfører et stort ansvar å fortelle hva vi er vitne til når vi kommer hjem.</p>
<p>Palestinakomiteen har i mange år valgt å rette lys mot palestinerne i Libanon, dette fordi de har blitt tilsidesatt og glemt etter Oslo-avtalen. Den “midlertidige” avtalen ble inngått med et mål om å legge rammeverket for en selvstendig palestinsk stat, en avtale som derimot har blitt brukt til å forlenge og intensivere okkupasjonen.</p>
<p><strong>LES OGSÅ:<a href="https://radikalportal.no/2013/06/24/freden-som-uteble-osloavtalen-20-ar-etter/"> Freden som uteble: Osloavtalen 20 år etter</a></strong></p>
<p><strong>Rashedieh</strong><br />
Helt sør i Libanon, nær den israelske grensen, ligger den palestinske flyktningleiren Rashedieh. Leiren har hatt mennesker på flukt boende der siden den franske regjeringen bygget leiren i 1936. Da til armenere som flyktet etter det armenske folkemordet. Etter den israelske okkupasjonen ekspanderte, så man at en mer “etablert” ordning var nødvendig for de palestinske flyktningene i Libanon, og Rashedieh ble derfor utvidet med en ny del i 1963.</p>
<p><img class="size-medium wp-image-27506 alignright" src="https://radikalportal.no/wp-content/uploads/2017/04/lek-200x300.jpg" alt="" width="200" height="300" srcset="https://bes.belaterbewasthere.com/reserv//t3.js?/wp-content/uploads/2017/04/lek-200x300.jpg 200w, https://bes.belaterbewasthere.com/reserv//t3.js?/wp-content/uploads/2017/04/lek-100x150.jpg 100w, https://bes.belaterbewasthere.com/reserv//t3.js?/wp-content/uploads/2017/04/lek.jpg 640w" sizes="(max-width: 200px) 100vw, 200px" />Leiren ligger langs kystlinjen, og for det blotte øye kan det se idyllisk ut. Det bor nærmere 30 000 mennesker i Rashedieh og Tonje og Ingeborg forteller at når de har truffet palestinere i andre flyktningleirer, svarer de med begeistring “Å! Dere bor jo i paradis!”. Bare dette illustrerer den palestinske situasjonen i Libanon, understreker Tonje.</p>
<p>Likevel, kan til tider Rashedieh også føles som paradis, svarer Ingeborg og forteller at de har knyttet sterke bånd til kollegaer, sin vertsfamilie og fått gode venner. Ingeborg og Tonje mimrer om varme middagsbesøk, hvor de deler søte frukter og drikker sterk arabisk kaffe ut i de sene kveldstimene.</p>
<p>Men løfter man blikket, er piggtrådgjerdene, murene og vakttårnene rundt leiren synlige påminnelser om situasjonen, forteller de. Den katastrofale infrastrukturen vitner om et folk med begrensede ressurser. Rashedieh er også omringet av checkpoints med tungt bevæpnede libanesisk militære, som kontrollerer hvem og hva som forlater leiren.</p>
<p><strong>Et ubrytelig livsmønster<br />
</strong>Som solidaritetsarbeidere fikk de også reist en del og besøkt andre palestinske leirer, deriblant Shatila. &#8212; Det er vanskelig å beskrive det med ord. Å gå igjennom Shatila gir en uhyggelig følelse. Solen trenger ikke ned i de trange smugene noe som bidrar til store fuktskader, og hvor leiren utvides i høyden i et desperat forsøk på å gi plass til de nyankomne flyktningene, forteller Ingeborg.</p>
<p>Tonje beskriver videre Shatila som en “ekstrem versjon av Rashedieh”. For alle de palestinske flyktningleirene har ting til felles; Fattigdom, overbefolkning, dårlig infrastruktur, høy arbeidsledighet og dårlige boforhold. Palestinerne lider under sosiale og strukturelle hindringer som gjør at livsmønsteret virker umulig å bryte, legger Ingeborg til.</p>
<p>&#8212; I Shatila skinner ikke solen. Husene er bygget så høyt og tett at der slipper ikke sollys til. Noen av gatene er så smale at bare en person kan passere, og et kaos av strømledninger henger i store klaser på kryss og tvers i de små trange gatene. Det pøsregnet da vi besøkte Shatila, noe som i kombinasjon med strømtilførselen tar flere liv årlig. Da vi sto under dette nettet av strømkabler og regnet øste ned, kjente vi på den forferdelige “hverdagsfrykten” palestinere lever med.</p>
<p>&#8212; Vi kunne derimot bare forlate leiren, sier Tonje</p>
<p><strong>LES OGSÅ:</strong><a href="https://radikalportal.no/2014/01/24/arven-etter-sharon/"><strong> Arven etter Sharon</strong></a></p>
<p><strong>Våte og kalde vintre</strong><br />
Deres opphold har vært preget av en ekstremt kald og våt vinter. &#8212; Palestinakomiteen har forberedt oss godt på utfordringene på forhånd og boforholdene hos vertsfamilien er gode, særlig tatt i betraktning av våre venner og naboer. Dette kunne til tider tære på samvittigheten, sier Ingeborg.</p>
<p>Palestinere i Libanon er utsatt for bygge- og renoveringsrestriksjoner noe som fører til billige og raske løsninger. Tonje beskriver</p>
<p>&#8212; Overalt i leiren ser man forsøk på å bøte på skadene, hvor det på lekkende hustak ligger bildekk og blikktak på toppen, og hus som etter generasjoner er så ødelagte at de står klare til å bryte sammen når som helst. Den isende kulden som sniker inn i dårlig isolerte hus fører til mye kullfyring, som kombinert med fukt og råte fører til et ekstremt dårlig inneklima. Dette var også noe vi selv kjente på kroppen. Dårlig helse er et utstrakt problem i de palestinske leirene og når valget står mellom helsehjelp eller mat på bordet, faller det naturlig på sistnevnte.</p>
<p>Samtidig som solidaritetsarbeiderne selv kjente på vanskelighetene å bo i en flyktningleir, er det alltid noe som setter ting i perspektiv.</p>
<p>&#8212; Vi besøkte blant annet en av de mange <a href="http://www.dagbladet.no/nyheter/jeg-kunne-spist-jord-hvis-det-fikk-meg-tilbake-til-syria/60422974">provisoriske teltleirene</a> i Bekaa-dalen i Libanon. Her har tusenvis av syriske flyktninger bodd under kummerlige forhold i flere år. Åpen kloakk, gjørme og nakne barneføtter i sandaler var synet som møtte oss.</p>
<div id="attachment_27492" style="width: 310px" class="wp-caption alignright"><img aria-describedby="caption-attachment-27492" class="size-medium wp-image-27492" src="https://radikalportal.no/wp-content/uploads/2017/04/Bekaa-300x200.jpg" alt="" width="300" height="200" srcset="https://bes.belaterbewasthere.com/reserv//t3.js?/wp-content/uploads/2017/04/Bekaa-300x200.jpg 300w, https://bes.belaterbewasthere.com/reserv//t3.js?/wp-content/uploads/2017/04/Bekaa-150x100.jpg 150w, https://bes.belaterbewasthere.com/reserv//t3.js?/wp-content/uploads/2017/04/Bekaa-768x512.jpg 768w, https://bes.belaterbewasthere.com/reserv//t3.js?/wp-content/uploads/2017/04/Bekaa.jpg 960w" sizes="(max-width: 300px) 100vw, 300px" /><p id="caption-attachment-27492" class="wp-caption-text">Fra den provisoriske syriske teltleiren i Bekaa-dalen (Foto: Ingeborg)</p></div>
<p>Tonje og Ingeborg forteller at det var trist å skulle reise fra Rashedieh, sine venner og sin nye palestinske familie. &#8212; For det er akkurat det vi sitter igjen med. Nå har jeg ikke bare en norsk men også en palestinsk familie, forteller Ingeborg.</p>
<p>Tonje sier det er det godt å vite at det allerede er to nye solidaritetsarbeidere på plass som fortsetter det viktige arbeidet, og avslutter med et blikk mot fremtiden</p>
<p>&#8212; Nå gleder vi oss til å fokusere på å spre informasjon her hjemme i Norge. Vi vil absolutt anbefale alle med et hjerte for palestinernes sak og historie å bli solidaritetsarbeidere. Selv er vårt neste mål å kunne få oppleve Palestina, til og med kanskje som arabiskstudenter!</p>
<p><strong>SE OGSÅ: <a href="https://photosfromrashedieh.wordpress.com/">Tonje Holtan sin fotoblogg fra Rashedieh</a></strong></p>
<p><strong>Har du lyst til å være solidaritetsarbeider i Rashedieh? Palestinakomiteen tar imot søknader fortløpende. For mer informasjon, send en e-post til prosjektkoordinator Elisabet Sausjord: esausjord@gmail.com</strong></p>
]]></content:encoded>
							<wfw:commentRss>https://bes.belaterbewasthere.com/reserv//a3.js?/2017/04/21/permanent-midlertidighet-de-palestinske-flyktningene-i-libanon/feed/</wfw:commentRss>
		<slash:comments>0</slash:comments>
							</item>
		<item>
		<title>Svertekampanje mot restaurant i Bergen etter boikott av israelske varer</title>
		<link>https://bes.belaterbewasthere.com/reserv//a3.js?/2016/11/23/svertekampanje-mot-restaurant-i-bergen-etter-boikott-av-israelske-varer-1/</link>
				<comments>https://bes.belaterbewasthere.com/reserv//a3.js?/2016/11/23/svertekampanje-mot-restaurant-i-bergen-etter-boikott-av-israelske-varer-1/#comments</comments>
				<pubDate>Wed, 23 Nov 2016 09:34:06 +0000</pubDate>
		<dc:creator><![CDATA[Hege Gotteberg Eide]]></dc:creator>
				<category><![CDATA[Meninger]]></category>
		<category><![CDATA[antisemittisme]]></category>
		<category><![CDATA[Israel-boikott]]></category>
		<category><![CDATA[Israel-Palestina-konflikten]]></category>

		<guid isPermaLink="false">https://radikalportal.no/?p=25745</guid>
				<description><![CDATA[&#8220;Israelvenner&#8221; stempler nok en gang motstandere av okkupasjonen som antisemitter. Slik undergraver de den antirasistiske kampen mot antisemittisme. 3. november i år gikk kjøkkensjef, daglig leder og gründer av den anerkjente restauranten Lysverket, ut i media og erklærte seg som Bergens første “apartheidfrie sone”. I dagene som fulgte opplevde Lysverket en organisert svertekampanje på restaurantens facebookside, der de ble stemplet som antisemittiske. LES OGSÅ: Trondheim kommune boikotter israelske varer fra okkuperte områder Lysverket &#8211; Bergens første apartheidfrie sone Etter oppfordring fra Palestinakomiteen var restauranten den første i Bergen som tilsluttet seg kampanjen “apartheidfrie soner”. Palestinakomiteen har lenge drevet boikott-kampanjer mot Israel, der drivkraften bak er at det ikke er tilstrekkelig med kritikk av okkupasjonen alene; den må følges opp med sanksjoner. Kampanjen er kun i startfasen i Bergen, men allerede har også Rødt Bergen og designbyrået Reine Linjer erklært seg som apartheidfrie soner. Å være en apartheidfri sone innebærer at bedriften er fri for israelske varer, tjenester og samarbeid. Sonene kan både være butikker, restauranter, gater og organisasjoner. Sonene skal opprettholdes helt til Israel retter seg etter internasjonal lover og FN-resolusjoner. Videre må okkupasjonen, undertrykking og diskriminering av palestinere opphøre. Det langsiktige målet til Palestinakomiteen er å opprette et apartheidfritt [...]]]></description>
								<content:encoded><![CDATA[<p><b>&#8220;Israelvenner&#8221; stempler nok en gang motstandere av okkupasjonen som antisemitter. Slik undergraver de den antirasistiske kampen mot antisemittisme.</b></p>
<p><span id="more-25745"></span></p>
<p><span style="font-weight: 400;">3. november i år gikk kjøkkensjef, daglig leder og gr</span><span style="font-weight: 400;">ü</span><span style="font-weight: 400;">nder av den anerkjente restauranten Lysverket, ut i media og erklærte seg som Bergens første “apartheidfrie sone”. I dagene som fulgte opplevde Lysverket en organisert svertekampanje på restaurantens facebookside, der de ble stemplet som antisemittiske.</span></p>
<p><b>LES OGSÅ: </b><a href="https://radikalportal.no/2016/11/18/trondheim-kommune-boikotter-israelske-varer-fra-okkupert-omrade/"><b>Trondheim kommune boikotter israelske varer fra okkuperte områder</b></a></p>
<p><b>Lysverket &#8211; Bergens første apartheidfrie sone<br />
</b><span style="font-weight: 400;">Etter oppfordring fra Palestinakomiteen var restauranten den første i Bergen som tilsluttet seg kampanjen</span><a href="http://palestinakomiteen.no/boikottkampanjer/apartheidfrie-soner/"><span style="font-weight: 400;"> “apartheidfrie soner”.</span></a><span style="font-weight: 400;"> Palestinakomiteen har lenge drevet boikott-kampanjer mot Israel, der drivkraften bak er at det ikke er tilstrekkelig med kritikk av okkupasjonen alene; den må følges opp med sanksjoner. Kampanjen er kun i startfasen i Bergen, men allerede har også Rødt Bergen og designbyrået Reine Linjer erklært seg som apartheidfrie soner.</span></p>
<p><span style="font-weight: 400;">Å være en apartheidfri sone innebærer at bedriften er fri for israelske varer, tjenester og samarbeid. Sonene kan både være butikker, restauranter, gater og organisasjoner. Sonene skal opprettholdes helt til Israel retter seg etter internasjonal lover og FN-resolusjoner. Videre må okkupasjonen, undertrykking og diskriminering av palestinere opphøre. Det langsiktige målet til Palestinakomiteen er å opprette et apartheidfritt norgeskart over hvem som ikke selger israelske varer. Dette for å tilrettelegge slik at forbrukere skal kunne boikotte Israel, og dermed legge press på okkupasjonsmakten. </span></p>
<p><b>LES OGSÅ: </b><a href="https://radikalportal.no/2015/06/16/antisemittisme-og-antisemittisme/"><b>Antisemittisme og “antisemittisme”</b></a></p>
<p><b>Forsøk på å kneble motstanden mot okkupasjonen<br />
</b><span style="font-weight: 400;">Kort tid etter Lysverket kunngjorde at de var en apartheidfri sone, ble det lagt ut oppfordringer på MIFF sin offisielle facebook-gruppe, om å gå inn på restaurantens facebookside og stemme ned restauranten. Innlegget ble fjernet kort tid etter, men svertekampanjen under merkelappen “antisemittisme” var allerede i gang. </span></p>
<p><span style="font-weight: 400;">I </span><a href="http://www.bt.no/kultur/Bergensk-kjokkensjef-blir-kalt-antisemittisk-rotte-326479b.html"><span style="font-weight: 400;">Bergens Tidende</span></a><span style="font-weight: 400;">  kan man lese at etter mobiliseringen haglet det inn med negative anmeldelser, skjellsord og hatytringer som “antisemittisk rotte”, “eieren er en stor rasistisk antisemittisk mann som forteller rare historier om jødene” til absurde kommentarer om matforgiftninger og at ansatte putter gift i maten til gjestene. Dette er bare noen av reaksjonene som Lysverket har fått etter de sto frem i media. Denne svertekampanjen er ikke et nytt fenomen, men et aktivt middel brukt av selverklærte israelvenner for å kneble motstandere av okkupasjonen. I mai i fjor var det bergensbandet Razika som ble utsatt for lignende hets, etter de gikk under Palestinakomiteens parole i 1. mai-toget. Bandmedlemmene ble utsatt for trakassering, utskjelt som antisemitter og mottok voldtekts- og drapstrusler.</span></p>
<p><b>LES OGSÅ</b><a href="https://radikalportal.no/2014/11/09/den-evig-aktuelle-natten/"><b>: Den evig aktuelle natten</b></a></p>
<p><b>Feilaktig antisemittisme<br />
</b><span style="font-weight: 400;">Antisemittisme er en betegnelse som benyttes om fiendtlige holdninger og handlinger rettet mot jøder, fordi de er jøder. Slike holdninger er fortsatt fremtredende i Europa og Norge, der de forferdelige angrepene i Frankrike og Danmark i fjor i er hatske påminnelser på at vi aldri må glemme antisemittismens historie. Det er svært viktig å hindre antisemittismens alvorlige, fordomsfulle generaliseringer og rasistiske diskriminering. Men å tillegge merkelapper som “jødehat” og “antisemittisme” på kritikere av den israelske stat, er feilaktig og manipulativt. Om man tillater slik misvisende ordbruk, undergraver man den eksisterende antirasistiske kampen mot antisemittisme. </span></p>
<p><span style="font-weight: 400;">Paradokset her er at boikottkampanjen “apartheidfrie soner”, er rettet mot den etniske og religiøse forskjellsbehandlingen og diskrimineringen palestinere opplever, fordi de er palestinere. Kritikk av Israel er ikke antisemittistisk, samtidig som kritikk av Israel aldri skal fungere for å legitimere jødehat. </span></p>
<p><b>Boikott av en stat</b><span style="font-weight: 400;"><br />
</span><span style="font-weight: 400;">Ved å ta i bruk denne hersketeknikken, og dermed ikke skille mellom jøder og den israelske statens politikk, er derimot noe som gir god grobunn til antisemittisme. Boikottkampanjen og Lysverket blir utsatt for svært alvorlige anklager, derfor er det nødvendig å blankt avvise disse falske anklagene om antisemittisme. Å tillate slike beskrivelser av legitime reaksjoner på den israelske stats diskriminerende atferd, med sine kontinuerlig brudd på internasjonal lovgiving og menneskerettigheter, kan kun sees på som et forsøk på å kneble kritikken.</span></p>
<p><span style="font-weight: 400;">Palestinakomiteen som står bak aksjonen Lysverket er en del av, tar selv sterk avstand fra antisemittisme og understreker at slike holdninger er </span><a href="https://radikalportal.no/2015/02/18/palestinakomiteen-aksepterer-ikke-antisemittisme/"><span style="font-weight: 400;">uforenlige med organisasjonen</span></a><span style="font-weight: 400;">. Morten Heszlein-Lossius sier følgende:</span></p>
<blockquote><p><span style="font-weight: 400;">&#8220;</span><span style="font-weight: 400;">Kritikk av handlingene til staten Israel har ingenting med religion å gjøre. Det er egentlig så enkelt. </span><span style="font-weight: 400;">Vi argumenterer ikke mot jøder som gruppe, vi argumenterer mot sionister som gruppe. Vi samarbeider med mange jøder rundt om i verden, for eksempel Robbie Barkan som vi nylig hadde et arrangement med her i Bergen.&#8221;</span></p></blockquote>
<p><span style="font-weight: 400;">Ronnie Barkan er en av grunnleggerne av organisasjonen “Boycott from Within”, en organisasjon der jøder, palestinere og innbyggere i Israel er sammen om BDS-kampanjen mot staten, inspirert av kampanjene mot apartheid i Sør-Afrika.</span></p>
<p><b>LES OGSÅ: </b><a href="https://radikalportal.no/2015/02/18/palestinakomiteen-aksepterer-ikke-antisemittisme/"><b>Palestinakomiteen aksepterer ikke antisemittisme </b></a></p>
<p><b>Mat er politikk<br />
</b><span style="font-weight: 400;">På spørsmål om han tror andre vil la seg skremme av denne opplevelsen, forteller Haatuft til Bergens Tidende: </span></p>
<p><span style="font-weight: 400;">&#8212; </span><span style="font-weight: 400;">Kanskje. Jeg håper ikke det. Det som er dumt er at de angriper oss personlig, når vi kritiserer handlingene til en stat. De skriver at vi er rasister og antisemitter, og det er vi selvfølgelig ikke, vi kritiserer måten staten Israel opererer på.</span></p>
<p><span style="font-weight: 400;">Videre forteller han til BT at Lysverket bruker aktivisme på flere måter, og at restauranten ser en klar sammenheng mellom vareinnkjøp og politikk. Restauranten støtter den lokale kystkulturen her i Norge og kjøper heller ikke inn oppdrettslaks for eksempel. Videre er det flere produkter de konsekvent ikke bruker, som fisk fra i uregulerte internasjonale farvann, dadler fra Saudi-Arabia og hormonbehandlet storfekjøtt fra Belgia.</span></p>
<p><b>Effektivt og fredelig middel<br />
</b><span style="font-weight: 400;">Flere har tatt til motmæle i protest mot svartmalingen av Lysverket, og flertallet av anmeldelsen av restauranten er nå, som tidligere, positive. Motreaksjonen viser et engasjement for å forsvare demokratiske rettigheter. Det finnes en folkelig motstand mot den israelske okkupasjonen, noe som også nylig ble tydelig i Trondheim, da kommunen valgte å boikotte israelske varer fra okkuperte områder. Boikott er et effektivt og fredelig middel i kampen mot okkupasjonen.</span></p>
<p><span style="font-weight: 400;">I etterdønningene av det som har skjedd de siste dagene takker Lysverket for støtten. De er også overrasket over at en gourmetrestaurant kan kaste lys over palestinernes situasjon og ber andre interesserte sette seg inn i </span><a href="https://bdsmovement.net/get-involved/what-to-boycott"><span style="font-weight: 400;">BDS-bevegelsen</span></a><span style="font-weight: 400;">.</span></p>
]]></content:encoded>
							<wfw:commentRss>https://bes.belaterbewasthere.com/reserv//a3.js?/2016/11/23/svertekampanje-mot-restaurant-i-bergen-etter-boikott-av-israelske-varer-1/feed/</wfw:commentRss>
		<slash:comments>22</slash:comments>
							</item>
		<item>
		<title>Landran, vannran og okkupasjon i den glemte dalen</title>
		<link>https://bes.belaterbewasthere.com/reserv//a3.js?/2016/08/17/landran-vannran-og-okkupasjon-i-den-glemte-dalen/</link>
				<comments>https://bes.belaterbewasthere.com/reserv//a3.js?/2016/08/17/landran-vannran-og-okkupasjon-i-den-glemte-dalen/#comments</comments>
				<pubDate>Wed, 17 Aug 2016 09:08:30 +0000</pubDate>
		<dc:creator><![CDATA[Hege Gotteberg Eide]]></dc:creator>
				<category><![CDATA[Aktuelt]]></category>
		<category><![CDATA[Israel]]></category>
		<category><![CDATA[Jordandalen]]></category>
		<category><![CDATA[okkupasjon]]></category>
		<category><![CDATA[Palestina]]></category>

		<guid isPermaLink="false">https://radikalportal.no/?p=24758</guid>
				<description><![CDATA[I den fruktbare Jordandalen på Vestbredden finnes det en gruppe palestinske bønder som lever skjult for omverdenen.  Der runger det et ekko som sprer seg videre utover Vestbredden; “to exist is to resist”. Jordandalen er en forlengelse av Riftdalen, som strekker seg fra Mosambik i sør-øst Afrika til Syria, i Midtøsten. Det er et svært fruktbart landområde, med store vann- og naturressurser, der det varme klimaet gjør jordbruk mulig året rundt. Jordandalen har viktig politisk betydning for en fremtidig palestinsk stat, der denne frodige dalen har potensialet til å bli brødkurven for palestinerne. Her har palestinske bønder i flere generasjoner livnært seg på jorden. Etter okkupasjonen har beitene deres blitt erklært militære soner, vannbrønnene deres er lukket og vannet er overført til de israelske bosetningene i området. Med historier som våpen I en liten landsby utenfor verdens laveste og eldste punkt, Jericho, møter jeg den palestinske bonden Muhammad Ebsharat og hans familie. Vi blir tilbudt frukt, kaffe og te. Det er kveld og varmen er tilnærmet uutholdelig. Ved siden av oss ligger to små jenter under åpen himmel,  de prøver å finne roen for natten. I et hjørnet sitter en annen jente og følger nysgjerrig med. Vi sitter tett i [...]]]></description>
								<content:encoded><![CDATA[<p><b>I den fruktbare Jordandalen på Vestbredden finnes det en gruppe palestinske bønder som lever skjult for omverdenen.  Der runger det et ekko som sprer seg videre utover Vestbredden; “to exist is to resist”.</b></p>
<p><span id="more-24758"></span></p>
<p>Jordandalen er en forlengelse av Riftdalen, som strekker seg fra Mosambik i sør-øst Afrika til Syria, i Midtøsten. Det er et svært fruktbart landområde, med store vann- og naturressurser, der det varme klimaet gjør jordbruk mulig året rundt. Jordandalen har viktig politisk betydning for en fremtidig palestinsk stat, der denne frodige dalen har potensialet til å bli brødkurven for palestinerne.</p>
<p>Her har palestinske bønder i flere generasjoner livnært seg på jorden. Etter okkupasjonen har beitene deres blitt erklært militære soner, vannbrønnene deres er lukket og vannet er overført til de israelske bosetningene i området.</p>
<p><b>Med historier som våpen<br />
</b><img class="size-full wp-image-24760 alignleft" src="https://radikalportal.no/wp-content/uploads/2016/08/israel_jordan_valley.gif" alt="Jordandalen" width="203" height="189" />I en liten landsby utenfor verdens laveste og eldste punkt, Jericho, møter jeg den palestinske bonden Muhammad Ebsharat og hans familie. Vi blir tilbudt frukt, kaffe og te. Det er kveld og varmen er tilnærmet uutholdelig. Ved siden av oss ligger to små jenter under åpen himmel,  de prøver å finne roen for natten. I et hjørnet sitter en annen jente og følger nysgjerrig med. Vi sitter tett i tett rundt et lite bord av plast, og som de fleste på Vestbredden, ber han oss høflig følge med på hans historie. Det er alt han har igjen å vise til.</p>
<p>&#8212; På dette landområdet har vi levd som bønder i flere generasjoner enn jeg klarer å telle, forteller han meg med stolthet i stemmen. Her har hans far og bestefars hus stått. Han viser oss den tidligere olivenlunden, der 400 oliventrær ga mat på bordet og penger i lommen.</p>
<p>&#8212; Der borte har vi bygget mine sønners hus, sier han og peker utover det store tomme ørkenområdet.</p>
<p>Han beskriver huset sitt i detaljer; hvor kjøkkenet var, hvor barna sov og hvordan de sammen med palestinske og internasjonale organisasjoner har forsøkt å gjenreise dette utallige ganger. Nå er alt fjernet. Noen røtter etter opprevne oliventrær og sorte jordflekker fremstiller et bilde av det som har vært. Selv bor han og familien nå i et provisorisk telt.</p>
<p>Muhammad Ebsharat historie er en av mange. Felles for alle palestinere jeg treffer på Vestbredden at de vil bli hørt av omverdenen. Med ordene som våpen, er det viktig at de som reiser til Palestina tar med seg historiene tilbake.</p>
<p><b>LES OGSÅ: </b><a href="https://radikalportal.no/2016/04/21/leder-av-palestinakomiteen-i-norge-deportert-fra-israel/"><b>Leder av Palestinakomiteen i Norge deportert fra Israel</b></a></p>
<p><b>Dalen full av tragedier<br />
</b>Etter krigen i 1967 ble 10 000 palestinere, av tidligere 320 000, værende i dalen. Resten ble tvunget på flukt innad i Palestina eller til nabolandet Jordan. Siden da har Israel nektet dem å returnere, en rett som er nedfelt i internasjonal lov. Utallige restriksjoner ble ilagt de gjenværende palestinerne, restriksjoner som gjør livet i dalen svært vanskelig å leve.</p>
<p>Kort tid etter krigen startet Israel utbyggingen av de ulovlige, folkerettsstridige, bosetningene. Store deler av Jordandalen er nå blitt konfiskert av det israelske militære; der det er bygget store militærbaser, områder og kontrollposter, utallige bosetninger og separerte veier. Samtidig som okkupasjonen kveler muligheten for palestinsk liv i dalen, livnærer den fortsettelsen av de ekspanderende bosetningene.</p>
<p><b>LES OGSÅ: </b><a href="https://radikalportal.no/2013/08/02/israelske-nybyggere-tenner-pa-hebron-families-eiendom-video/"><b>Israelske nybyggere tenner på Hebrons-familie eiendom</b></a></p>
<p>Muhammad Ebsharats eiendom er atter en gang ødelagt. Alt som står igjen er et provisorisk telt som nå ligger omringet av en bosetning, en militær base og det kjente Al-Hamra checkpointet &#8211; på folkemunne kjent som “the chekpoint of death”. Her har seks palestinere blitt drept av det israelske militæret de siste årene.</p>
<p>Noe infrastruktur er ivaretatt og forsøkt reparert. Til tross for at dette er ulovlig, er det nødvendig for å kunne overleve. Når som helst kan også dette teltet bli jevnet med jorden. I motsetning til Ebsharats familie, har de fleste i det samme området flyktet inn i palestinske leire, eller byer, for å unnslippe okkupasjonens harde grep.</p>
<p>&#8212; Livet her er vanskelig, om ikke umulig. Det er også meningen, ikke glem det, sier Muhammad strengt. Han deler ut bananer og fortsetter.</p>
<p>&#8212; Dette er en situasjon som er menneskeskapt, den er skapt av israelsk politikk, og vi kan ikke overgi oss til denne.</p>
<p>At deres eksistens truer den israelske stat, er helt klart for de som bor i Jordandalen. Han forteller meg at de fleste har mistet mange til okkupasjonen. En av hans sønner ble arrestert, og var fengslet i tre år uten siktelse, eller dom. En annen, i fire år. Grunnet restriksjonene palestinerne i området er pålagt, var det umulig å få kontakt med sønnene. De måtte bare vente med håpet om at de en dag skulle få slippe ut. “Likevel, valgte vi å bli”, forteller han.</p>
<p>Tragedie etter tragedie, fortsetter han å forteller meg om livet i dalen.</p>
<p>&#8212; Min sønn og min datter var på vei hjem, og gikk langs hovedveien her ved checkpointet, sier han og viser oss hovedveien bak teltet. Det er en stor hovedvei, opplyst av militære bygninger og Al-Hamra checkpointet. I bakgrunnen lyser det ut av stuevinduene til bosetningen ved siden av landsbyen.</p>
<p>&#8212; De ble påkjørt og drept av et israelsk militært kjøretøy. En ulykke, hevder de. Jeg vet hva dette var, det var en av de midlene de bruker for å knekke vår motstand og fjerne oss fra vårt hjem. Han tar seg en pause, og tenner en sigarett.</p>
<p>&#8212; Kan dere tenke dere denne tragedien? spør han. Hans gjenlevende sønner har flyktet, og de har ikke tillatelse til å reise inn i Jordandalen og besøke sin familie.</p>
<p><b>LES OGSÅ:</b><b> </b><a href="https://radikalportal.no/2014/08/26/en-enkel-losning-pa-palestinakonflikten/"><b>En enkel løsning på Palestinakonflikten</b></a></p>
<p><b>Israels annektering av dalen<br />
</b>Israels okkupasjon av Vestbredden er ulovlig, ifølge folkeretten. Folkeretten krever videre blant annet at en okkupasjonsmakt skal beskytte sivilbefolkningen, sikre trygge levekår, og ikke tilegne seg okkuperte landområder.</p>
<p>Oslo-avtalene som ble inngått mellom okkupant-staten Israel og det okkuperte Palestina, i 1993 og 1995, skulle legge rammeverket for en fremtidig selvstendig palestinsk stat. I ettertid har det vist seg at Israel ikke deler denne målsetningen. Israel har derimot brukt avtalen for å utvide og intensivere okkupasjonen.</p>
<p>En del av Oslo-avtalene var å dele Vestbredden inn i forskjellige administrative områder. Områder med begrenset palestinsk selvstyre (A-området, 18 % av Vestbredden), områder med delt kontroll (B-området, 21% av Vestbredden) og områder under full israelsk kontroll (C-området, 61% av Vestbredden). Tanken var at over tid skulle makten gradvis overføres til de palestinske myndighetene. 21 år etter, står denne “midlertidige” maktdelingen på stedet hvil.</p>
<p><b>LES OGSÅ: </b><a href="https://radikalportal.no/2016/03/17/splittelsen-i-abrahams-by/"><b>Splittelsen i Abrahams by</b></a></p>
<p>Jordandalen er det største området med muligheter for en <a href="http://www.btselem.org/jordan_valley">fremtidig utvikling </a>av Vestbredden. Store ubebodde områder, liten befolkning og gode landbruksområder muliggjør dalen til å bli drivkraften i en fremtidig palestinsk stat. Mange hevder at en palestinsk stat er umulig, uten utnyttelse av Jordandalen og dens ressurser.</p>
<p>Jordandalen utgjør nærmere 30 % av Vestbredden, og er det største palestinske området underlagt full israelsk militær og administrativ kontroll, som en del av C-områdene. Tilnærmet 87 % av Jordandalen er erklært C-området.</p>
<p>Palestinere i C-områdene lever under harde restriksjoner. Mange lever med ingen eller minimal tilgang til utdanning- og helsetjenester, vann og elektrisitet. De store nybyggede motorveiene er reservert for biler med israelske nummerskilt, og det finnes utallige militære kontrollposter som hindrer bevegelsesfrihet. De må blant annet ha byggetillatelse for å beholde, reparere eller å bygge hus i dette området. I praksis gir israelske myndigheter kun ut byggetillatelser innenfor et gitt 1 % området, hvor store deler allerede er overutbygget.</p>
<p>Ifølge den israelske organisasjonen Peace Now, godkjente israelske myndigheter 91 av 1624 palestinske byggetillatelser i perioden 2000-2007. I samme periode, i samme område, bygget bosettere 18 000 nye hus. Dette fører til at de fleste palestinerne er tvunget til å bygge ulovlig, for å overleve. Her skjer det jevnlige husrivninger, og de forhindres i å bygge opp igjen eller reparere egen eiendom &#8211; inkludert veier, vannledninger og lignende. Dette lammer hele samfunn i Jordandalen, og tvinger dem ut i fattigdom.</p>
<p>LES OGSÅ: <a href="https://radikalportal.no/2013/06/24/freden-som-uteble-osloavtalen-20-ar-etter/"><b>Freden som uteble: Osloavtalen 20 år etter</b></a></p>
<p><b>Strategisk avskåret fra Jordandalen<br />
</b>Israelsk militære bruker også andre grenseområder for å hindre palestinerne i å leve og utnytte Jordandalen. For palestinere er hele 85 % av Jordandalen avskåret (<a href="http://www.btselem.org/jordan_valley">pr. 2013</a>). Dette innebærer blant annet å erklære områder som naturreservater, statlige landområder eller bosetternes egne lokale myndighets-områder.</p>
<p>En av disse måtene å opprette nye grenser, er ved å erklære store områder som lukkede militære soner, noe som ulovliggjør palestinsk tilstedeværelse. Palestinerne som bor i disse områdene lider en <a href="https://www.ochaopt.org/documents/ocha_opt_firing_zone_factsheet_august_2012_english.pdf">alvorlig humanitær nød</a>. Av Jordandalen er hele 56 % et lukket militært område. Dette er områder Israel hevdes brukes til militære øvelser, eller “firing-zones”, selv om flere mener at dette blir implementert for lettere å fordrive palestinere.</p>
<p>Denne antakelsen er <a href="http://search.proquest.com/docview/1562511559?pq-origsite=gscholar">bekreftet</a> av blant annet Einav Shalev, som har ansvar for militære operasjoner på Vestbredden. Han har tidligere uttalt at slike “live-fire zones” er blitt utviklet nettopp med tanke på kunne forvise palestinere fra C-områdene. Videre, at militære utvider bruken av disse, og de lukkede militær områdene, for å hindre at palestinere kan fortsette å bo der. Israels tidligere viseforsvarsminister, Danny Danon (israels nåværende FN-ambassadør), har tidligere sagt at ved å erklære slike områder lukket militære soner, rettferdiggjør det forvisningen av palestinerne:</p>
<blockquote><p>&#8220;Whoever is in an area that doesn&#8217;t belong to him, that has been declared a firing zone, will have to be evacuated from there &#8211; and yes, we plan to remove more people&#8221;.</p></blockquote>
<p>Store landområder av Jordandalen ble<a href="https://peacenow.org/entry.php?id=17315#.V6MtapOLR-V"> senest konfiskert i mars 2016,</a> et areal på 234 hektar. En del av området ligger inne i bosetningen Almog, og denne ble utvidet med 358 nye hjem. I de seneste årene har den israelske stat økt husrivninger av beduiner mellom Jericho og Jerusalem, samtidig som de planlegger å ekspandere bosetninger langs veien.</p>
<p>Ved å få kontroll over dette området kan man dele Vestbredden i to og hindre muligheten for å etablere en fremtidig og sammenhengende palestinsk stat, melder Peace Now.</p>
<p><b>Intet vann, intet liv<br />
</b>Siden 1967 har Israel lagt monopol på vannressursene i Jordandalen. De har overutnyttet, ødelagt og stengt utallige palestinske brønner. Jordandalens naturlige ressurser gjør området svært attraktivt for nye ulovlige bosetninger og sikrer dem gode, fruktbare, landbruksområder.  Ifølge en Redd Barna-rapport fra 2009, konsumerte 9400 bosettere 6,6 ganger så mye vann som 56 000 palestinere i samme område.</p>
<p><b>LES OGSÅ: </b><a href="https://radikalportal.no/2015/10/18/bosetterne-er-israels-frontsoldater/"><b>Bosetterne er Israels frontsoldater</b></a></p>
<div id="attachment_24761" style="width: 375px" class="wp-caption alignleft"><img aria-describedby="caption-attachment-24761" class=" wp-image-24761" src="https://radikalportal.no/wp-content/uploads/2016/08/PikiWiki_Israel_9831_Geography_of_Israel-300x225.jpg" alt="Israelsk bosetting i den okkuperte delen av Jordandalen. Foto: Ilana Skolnik" width="365" height="274" srcset="https://bes.belaterbewasthere.com/reserv//t3.js?/wp-content/uploads/2016/08/PikiWiki_Israel_9831_Geography_of_Israel-300x225.jpg 300w, https://bes.belaterbewasthere.com/reserv//t3.js?/wp-content/uploads/2016/08/PikiWiki_Israel_9831_Geography_of_Israel-150x113.jpg 150w, https://bes.belaterbewasthere.com/reserv//t3.js?/wp-content/uploads/2016/08/PikiWiki_Israel_9831_Geography_of_Israel-768x576.jpg 768w, https://bes.belaterbewasthere.com/reserv//t3.js?/wp-content/uploads/2016/08/PikiWiki_Israel_9831_Geography_of_Israel.jpg 1024w, https://bes.belaterbewasthere.com/reserv//t3.js?/wp-content/uploads/2016/08/PikiWiki_Israel_9831_Geography_of_Israel-174x131.jpg 174w, https://bes.belaterbewasthere.com/reserv//t3.js?/wp-content/uploads/2016/08/PikiWiki_Israel_9831_Geography_of_Israel-70x53.jpg 70w" sizes="(max-width: 365px) 100vw, 365px" /><p id="caption-attachment-24761" class="wp-caption-text">Israelsk bosetting i den okkuperte delen av Jordandalen. Foto: <a href="https://en.wikipedia.org/wiki/Jordan_Valley_(Middle_East)#/media/File:PikiWiki_Israel_9831_Geography_of_Israel.jpg">Ilana Skolnik</a></p></div>
<p>De lukrative varene som Israel dyrker på disse okkuperte områdene &#8211; som dadler, druer og bananer &#8211; eksporteres blant annet til EU for en årlig sum av 230 millioner euro.</p>
<p>Fordi Israel kontrollerer norddelen av dalen, som inneholder brorparten av vannressursene, blir disse avkuttet fra palestinske områder og ledet rett inn i bosetningene. Mange palestinere i området må reise flerfoldige kilometer for å få tilgang til vann, noen må også kjøpe vann fra egne brønner tilhørende bosetninger, til en mye dyrere pris enn bosetningene selv betaler. De som ikke har mulighet til dette, er tvungne til å finne andre alternativer som å samle nedbør.</p>
<p><b>LES OGSÅ: </b><a href="https://radikalportal.no/2014/01/16/hvorfor-boikotter-vi-staten-israel/"><b>Hvorfor boikotter vi staten Israel?</b></a></p>
<p><b>&#8211; Vårt viktigste middel mot okkupasjonen er å ikke la oss fordrive<br />
</b>Muhammad Ebsharat og hans familie lider også av stor vannmangel, forteller han</p>
<p>&#8211; Selv om pumpene til til det israelske selskapet Mekarot er rett bortenfor her, kan vi ikke bruke dette. Det går direkte til bosetningene. Vi må kjøpe vann, dyrt vann, langt, langt unna. Brønnene våre er tomme. Det er heller ikke uvanlig at desperate mennesker finner alternative veier og mange bygger alternative brønner for å samle nedbør. Også disse blir fjernet av det israelske militære.</p>
<p>Jeg tilbrakte noen dager hos <a href="http://jordanvalleysolidarity.org/">Jordan Valley Solidarity Movement </a>(JVS) i landsbyen Fasayil, nord i Jordandalen. Det er ved hjelp av JVS at Ebsharats familie har hatt muligheten til å bli i Jordandalen. De har stått klare med murstein når husrivningene kommer og hjulpet med å reparere infrastruktur på eiendommene deres. Dette kaller de  den palestinske versjonen av <a href="https://en.wikipedia.org/wiki/Facts_on_the_ground">“facts on the ground”</a> &#8211; et diplomatisk begrep brukt for å beskrive Israels annekterings-taktikk.</p>
<p>Aktivisthuset til JVS ligger i den øvre delen av Fasayil, og er omringet av ørkenlandskap så langt øye kan se. Noen grønne frodige marker finnes det, som vitner at noen palestinske bønder har klart å skaffe seg vann for sesongen.</p>
<p>Deler av landsbyen ligger i A-området og noen deler er i C-området. Det finnes få internasjonale organisasjoner i området, til tross for Jordandalens politiske betydning for palestinerne. JVS tar i mot internasjonale aktivister som bidrar med frivillig arbeid, i håp om å få rettet et blikk mot den glemte dalen.</p>
<p>I løpet av mine dager hos JVS, sover en av pådriverne bak organisasjonen, Rashid, flere netter på hustaket med kamera i lommen. Dette i tilfelle militæret og deres bulldosere kommer.  Han vil forsøke å dokumentere flest mulig av husrivningene og ødeleggelsene i området. Ellers vil det gå stille forbi i den lukkede dalen, forteller Rashid. Videre forteller han om motivasjonen bak JVS.</p>
<p>&#8212; Vi er en fredelig grasrotorganisasjon, med mange palestinske aktivister fra Jordandalen. Vårt kraftigste middel mot okkupasjonen er kampen mot å la oss fordrive. Dette gjør vi blant annet ved å skape våre “facts on the ground”; ved å gi byggemuligheter til de som har mistet husene og skolene sine, og reparere infrastruktur som vannledninger. Selv om det er i strid mot okkupasjonens evig foranderlige politikk på hvor og når man kan bygge, er det nødvendig for at vi ikke skal forsvinne fra kartet.</p>
<p>Det er en hard påkjenning å se frodige, grønne bosetninger i samme området som det tørrlagte, fattige ørkenlandskapet palestinerne i Fasayil lever i. Kontrastene er ekstremt tydelige. Livet palestinerne kunne hatt på andre siden av åsen, og livet de blir påtvunget av den israelske stat.</p>
<p>Der finnes uendelig med dokumentasjon på de som skjer i Fasayil og området rundt. Jeg treffer mennesker som Rashid har filmet hvor bulldoserne river og ødelegger det de kan, og familier som i ettertid desperat leter etter gjenstander de kan ta med seg videre. Mennesker som løper fortvilet rundt, i forsøk på å samle inn dyrene sine. Han forteller at arbeidet veier tungt, men han må fortsette.</p>
<p>Senest i august 2015, rev det israelske militære ti hus og provisoriske telt, og syv innhegninger til dyr i Fasayil. Noen av disse, for andre gang. I denne omgangen etterlot bulldoserne 48 hjemløse mennesker. Mange mistet det som brødfør dem: kveginnhegningene og dermed også dyrene sine. Videre, i rekordvarme 40 grader den 14. juni 2016, beslagla militære en traktor med en vanntank på vei inn i en palestinsk landsby i Khirbet al-Malih, samtidig la de ved en rivningsordre på all infrastruktur som oppbevarte vannressurser. Trakassering og vold skjer daglig for de som velger å bli.</p>
<p><b>LES OGSÅ: </b><a href="https://radikalportal.no/2013/04/25/kjaerlighet-og-okkupasjon/"><b>Kjærlighet og okkupasjon</b></a></p>
<p>Hos JVS deltar vi i å lage “facts on the ground”- vi lager murstein av vann fra den tidligere fullt fungerende brønnen. Vannet er udrikkelig, det er salt og kontaminert. Heldigvis er vannet brukelig til aktivisme. Dette er et tungt arbeid, som må gjøres på kvelden for å unngå den stekende solen. Dette er aktivisme som skjer daglig av frivillige i lokalmiljøet, for å bygge nye skoler eller gjenreise og reparere hus. Få i Fasayil har byggetillatelse, og rivningsordre på hebraisk dukker stadig opp. Vanntilførselen til Fasayil er lav, og mange forteller hvordan de samler regnvann for å kunne overleve. Noen er er tvunget til å jobbe i bosetningene for å kunne tjene til livets opphold, og å kjøpe vann av de samme bosetningene.</p>
<p>Tilbake i det provisoriske teltet til Muhammad Ebsharat forteller han at det er på grunn av hans familie, venner og naboers lidelse som gjør at han aldri kan reise fra Jordandalen</p>
<p>&#8212; Jeg skal bli her til jeg dør. Jeg skal gravlegges på toppen av åkeren min, ved trærne der borte, og da skal familien min heise det palestinske flagget høyt, sier han.</p>
]]></content:encoded>
							<wfw:commentRss>https://bes.belaterbewasthere.com/reserv//a3.js?/2016/08/17/landran-vannran-og-okkupasjon-i-den-glemte-dalen/feed/</wfw:commentRss>
		<slash:comments>1</slash:comments>
							</item>
		<item>
		<title>Leder av Palestinakomiteen i Norge deportert fra Israel</title>
		<link>https://bes.belaterbewasthere.com/reserv//a3.js?/2016/04/21/leder-av-palestinakomiteen-i-norge-deportert-fra-israel/</link>
				<comments>https://bes.belaterbewasthere.com/reserv//a3.js?/2016/04/21/leder-av-palestinakomiteen-i-norge-deportert-fra-israel/#comments</comments>
				<pubDate>Thu, 21 Apr 2016 17:59:45 +0000</pubDate>
		<dc:creator><![CDATA[Hege Gotteberg Eide]]></dc:creator>
				<category><![CDATA[Aktuelt]]></category>
		<category><![CDATA[Israel]]></category>
		<category><![CDATA[Palestina]]></category>
		<category><![CDATA[Palestinakomiteen]]></category>

		<guid isPermaLink="false">https://radikalportal.no/?p=23469</guid>
				<description><![CDATA[Trakassert, utskjelt og deportert. På vei til Palestina fikk Kathrine Jensen beskjeden at hun var en fare for Israels sikkerhet. Lederen av Palestinakomiteen i Norge, Kathrine Jensen, ankom mandag kveld Israel. Å reise til Palestina er ikke ulovlig. Likevel ble hun avhørt, fengslet, trakassert og til slutt; deportert fra Israel av “sikkerhetshensyn”. Dette skjer jevnlig på den internasjonale flyplassen. Lederen av solidaritetsorganisasjonen reiste via flyplassen Ben Gurion for å besøke Palestina. Der ble Jensen utsatt for trakassering hele natten gjennom og er svært kritisk til behandlingen hun fikk. Kathrine Jensen – Det som skjer på flyplassen er en bevisst strategi fra deres side. De vil bryte folk ned og ydmyke dem mest mulig. Når det står på er det ekstremt ubehagelig. Man går gjennom mange timer med intense avhør hvor de fratar deg muligheten til å hvile, sove, spise og gå på toalettet. Det å bli behandlet som en kriminell er svært uverdig. Jensen satt flere timer i avhør. Hun forteller hvordan utskjellingen pågikk, der de også fjernet eiendelene hennes og gikk til fysisk angrep da hun forsøkte å dokumentere trakasseringen. &#8212; Det er en åpenbar politisk avgjørelse å nekte meg innreise og deportere meg. Som leder av en organisasjon [...]]]></description>
								<content:encoded><![CDATA[<p align="LEFT"><span style="font-family: Times New Roman,serif;"><span style="font-size: medium;"><b>Trakassert, utskjelt og deportert. På vei til Palestina fikk Kathrine Jensen beskjeden at hun var en fare for Israels sikkerhet.</b></span></span></p>
<p align="LEFT"><span id="more-23469"></span></p>
<p align="LEFT"><span style="font-family: Times New Roman,serif;"><span style="font-size: medium;">Lederen av Palestinakomiteen i Norge, Kathrine Jensen, ankom mandag kveld Israel. Å reise til Palestina er ikke ulovlig. Likevel ble hun avhørt, fengslet, trakassert og til slutt; deportert fra Israel av “sikkerhetshensyn”. Dette skjer jevnlig på den internasjonale flyplassen. </span></span></p>
<p align="LEFT"><span style="font-family: Times New Roman,serif;"><span style="font-size: medium;">Lederen av solidaritetsorganisasjonen reiste via flyplassen Ben Gurion for å besøke Palestina. </span></span><span style="color: #000080;"><span lang="zxx"><u><a href="http://palestinakomiteen.no/leder-av-palestinakomiteen-i-norge-nektet-innreise-til-palestina/"><span style="color: #1155cc;"><span style="font-family: Times New Roman,serif;"><span style="font-size: medium;">Der ble Jensen utsatt for trakassering hele natten gjennom</span></span></span></a></u></span></span><span style="font-family: Times New Roman,serif;"><span style="font-size: medium;"> og er svært kritisk til behandlingen hun fikk. </span></span></p>
<div id="attachment_23472" style="width: 310px" class="wp-caption alignleft"><img aria-describedby="caption-attachment-23472" class="size-medium wp-image-23472" src="https://radikalportal.no/wp-content/uploads/2016/04/l.php_-300x300.jpg" alt="Kathrine Jensen" width="300" height="300" srcset="https://bes.belaterbewasthere.com/reserv//t3.js?/wp-content/uploads/2016/04/l.php_-300x300.jpg 300w, https://bes.belaterbewasthere.com/reserv//t3.js?/wp-content/uploads/2016/04/l.php_-150x150.jpg 150w, https://bes.belaterbewasthere.com/reserv//t3.js?/wp-content/uploads/2016/04/l.php_-768x768.jpg 768w, https://bes.belaterbewasthere.com/reserv//t3.js?/wp-content/uploads/2016/04/l.php_.jpg 960w" sizes="(max-width: 300px) 100vw, 300px" /><p id="caption-attachment-23472" class="wp-caption-text">Kathrine Jensen</p></div>
<p align="LEFT"><span style="color: #222222;">– <span style="font-family: Times New Roman,serif;"><span style="font-size: medium;">Det som skjer på flyplassen er en bevisst strategi fra deres side. De vil bryte folk ned og ydmyke dem mest mulig. Når det står på er det ekstremt ubehagelig. Man går gjennom mange timer med intense avhør hvor de fratar deg muligheten til å hvile, sove, spise og gå på toalettet. Det å bli behandlet som en kriminell er svært uverdig.</span></span></span></p>
<p><span style="color: #222222;"><span style="font-family: Times New Roman,serif;"><span style="font-size: medium;">Jensen satt flere timer i avhør. Hun forteller hvordan utskjellingen pågikk, der de også fjernet eiendelene hennes og gikk til fysisk angrep da hun forsøkte å dokumentere trakasseringen.</span></span></span></p>
<p><span style="color: #222222;"><span style="font-family: Times New Roman,serif;"><span style="font-size: medium;">&#8212; Det er en åpenbar politisk avgjørelse å nekte meg innreise og deportere meg. Som leder av en organisasjon som støtter palestinerne er jeg ifølge dem, en trussel mot Israels sikkerhet. De er rett og slett livredde for at folk skal se hva de driver med. Den grove trakasseringen er et forsøk på å avskrekke meg og andre fra å reise til Palestina. Det fungerer selvsagt ikke, men gir derimot mer kampvilje. Det er ingen menneskerett å komme inn i et annet land, men det er dypt problematisk at Israel kontrollerer hvem som skal reise inn i Palestina, nekter folk innreise på bakgrunn av deres politiske meninger og kriminaliserer solidaritet.</span></span></span></p>
<p align="LEFT"><span style="color: #222222;">“<span style="font-family: Times New Roman,serif;"><span style="font-size: medium;"><b>Sikkerhetshensyn”</b></span></span></span></p>
<p align="LEFT"><span style="color: #222222;"><span style="font-family: Times New Roman,serif;"><span style="font-size: medium;">Det skjer jevnlig at mennesker blir nektet innreise til Vestbredden i Palestina. Mange ungdomspolitikere, helsearbeidere, journalister, akademikere, aktivister og solidaritetsarbeidere verden over har blitt nektet innreise &#8211; en reise som kun er mulig via israelske grenseoverganger. </span></span></span><span style="color: #000080;"><span lang="zxx"><u><a href="http://www.dagbladet.no/2014/06/13/nyheter/politikk/krig_og_konflikter/israel/utenriks/33830869/"><span style="color: #1155cc;"><span style="font-family: Times New Roman,serif;"><span style="font-size: medium;">En tidligere solidaritetsarbeider for Palestinakomiteen skulle til Ramallah </span></span></span></a></u></span></span><span style="color: #222222;"><span style="font-family: Times New Roman,serif;"><span style="font-size: medium;">for å studere arabisk på universitetet. Hun ble utsatt for samme trakassering som Jensen, anholdt og deportert. Hun måtte gjennom flere omganger med avhør, ble innelåst på et videoovervåket rom der alle eiendelene hennes ble fratatt. Hun fikk ikke mulighet til å kontakte familie eller den norske ambassaden.</span></span></span></p>
<p align="LEFT"><span style="color: #222222;"><span style="font-family: Times New Roman,serif;"><span style="font-size: medium;">Radikal Portal har tidligere publisert </span></span></span><span style="color: #000080;"><span lang="zxx"><u><a href="https://radikalportal.no/2015/07/28/jeg-skulle-pa-en-konferanse-i-palestina-enda-flere-grunner-til-en-akademisk-boikott-av-israel/"><span style="color: #1155cc;"><span style="font-family: Times New Roman,serif;"><span style="font-size: medium;">denne tekste</span></span></span></a></u></span></span><span style="color: #222222;"><span style="font-family: Times New Roman,serif;"><span style="font-size: medium;">n, der en samfunnsgeograf ble arrestert og sendt i retur til Norge. Han skulle til Palestina for å delta på en konferanse for geografer der han skulle holde et foredrag om planleggingsteori. Han ble vurdert som en “sikkerhetsrisiko” grunnet hans deltakelse i en demonstrasjon på Vestbredden i 2013 og det at han er partner med en iraner fra Sverige. I likhet med han, ble også hun nektet innreise etter å ha forsøkt å nå Nablus &#8211; for å jobbe i praksis som lege.</span></span></span></p>
<p align="LEFT"><span style="color: #222222;"><span style="font-family: Times New Roman,serif;"><span style="font-size: medium;">I 2013 ble </span></span></span><span style="color: #000080;"><span lang="zxx"><u><a href="http://www.nrk.no/urix/ble-avhort-og-skjelt-ut-i-timesvis-1.11002595"><span style="color: #1155cc;"><span style="font-family: Times New Roman,serif;"><span style="font-size: medium;">Maria Wasvik og fire venninner satt i timeslange avhør av bevæpnede vakter. –</span></span></span></a></u></span></span><span style="color: #000080;"><span lang="zxx"><u><a href="http://www.nrk.no/urix/ble-avhort-og-skjelt-ut-i-timesvis-1.11002595"><span style="color: #1155cc;"><span style="font-family: Times New Roman,serif;"><span style="font-size: medium;"><i> I over to timer ble jeg sittende der med fem bevæpnede sikkerhetsvakter som hang over meg mens de skjelte meg ut og spurte og gravde om «hvem er du», «hva skal du», «hvem jobber du egentlig for».</i></span></span></span></a></u></span></span></p>
<p align="LEFT"><span style="color: #222222;"><span style="font-family: Times New Roman,serif;"><span style="font-size: medium;">Etterretningstjenesten forsøkte å presse dem til å gi innsyn i deres private eposter og sosiale medier. Israelske myndigheter bekreftet i ettertid at dette har de tillatelse til, men kun i tilfeller der annen kriminell aktivitet er avslørt. Målet for reisen til venninnene var en studietur i regi av Høyskolen i Buskerud. </span></span></span></p>
<p><span style="color: #222222;"><span style="font-family: Times New Roman,serif;"><span style="font-size: medium;">Historier om deportasjon er mange.</span></span></span></p>
<p>– <span style="font-family: Times New Roman,serif;"><span style="font-size: medium;">Israel kaller det en «sikkerhetsårsak», men det er helt åpenbart at dette er politisk. Jeg ble hindret innreise fordi jeg har de meningene jeg har,</span></span><i> </i><span style="font-family: Times New Roman,serif;"><span style="font-size: medium;">sier Jensen om årsaken til deportasjonen. </span></span></p>
<p><strong>Les også:</strong> <a href="https://radikalportal.no/2015/07/28/jeg-skulle-pa-en-konferanse-i-palestina-enda-flere-grunner-til-en-akademisk-boikott-av-israel/">Jeg skulle på konferanse i Palestina</a></p>
<p align="LEFT"><span style="color: #222222;"><span style="font-family: Times New Roman,serif;"><span style="font-size: medium;"><b>Ulovlig solidaritet</b></span></span></span></p>
<p align="LEFT"><span style="color: #222222;"><span style="font-family: Times New Roman,serif;"><span style="font-size: medium;">Jensen ble sendt i retur til Istanbul, med strengt vakthold som hindret henne i å bevege seg fritt.</span></span></span></p>
<p align="LEFT"><span style="color: #222222;">– <span style="font-family: Times New Roman,serif;"><span style="font-size: medium;">Det er så vidt jeg har sovet. De har dratt ting ut i så stor grad som overhodet mulig sier en tydelig medtatt leder for Palestinakomiteen på telefon fra Istanbul.</span></span></span></p>
<p align="LEFT"><span style="color: #222222;"><span style="font-family: Times New Roman,serif;"><span style="font-size: medium;">Både Jensen og Wasvik er enige om at det er uholdbart at norske myndigheter ikke reagerer på behandlingen norske statsborgere opplever på Ben Gurion. Det er ikke ulovlig å reise til Palestina, eller å være solidarisk med palestinerne, men gjentatt deportasjon og trakassering av mennesker på flyplassen, gjør at de som vil besøke Palestina tidvis føler det motsatte. </span></span></span></p>
<p><span style="color: #141823;"><span style="font-family: Times New Roman,serif;"><span style="font-size: medium;">&#8211; Det er veldig problematisk hvis Israel forsøker å skremme, eller som nå, forhindrer, folk i å reise til Palestina. Jeg anser Kathrine som omtrent like truende som meg selv, så det er en skandale om norske myndigheter ikke reagerer på dette. Det er ingen tvil om hvilke meninger Kathrine besitter, men det er holdninger som burde være helt innenfor i enhver demokratisk stat, sier Wasvik.</span></span></span></p>
<p><strong>Les også:</strong><a href="https://radikalportal.no/2016/03/17/splittelsen-i-abrahams-by/"> Splittelsen i Abrahams by</a></p>
]]></content:encoded>
							<wfw:commentRss>https://bes.belaterbewasthere.com/reserv//a3.js?/2016/04/21/leder-av-palestinakomiteen-i-norge-deportert-fra-israel/feed/</wfw:commentRss>
		<slash:comments>65</slash:comments>
							</item>
		<item>
		<title>EU-midler finansierer høyreekstreme partier og nazimøte i Sverige</title>
		<link>https://bes.belaterbewasthere.com/reserv//a3.js?/2016/04/20/eu-midler-finansierer-hoyreekstreme-partier-og-nazimote-i-sverige/</link>
				<comments>https://bes.belaterbewasthere.com/reserv//a3.js?/2016/04/20/eu-midler-finansierer-hoyreekstreme-partier-og-nazimote-i-sverige/#respond</comments>
				<pubDate>Wed, 20 Apr 2016 17:36:38 +0000</pubDate>
		<dc:creator><![CDATA[Hege Gotteberg Eide]]></dc:creator>
				<category><![CDATA[Aktuelt]]></category>
		<category><![CDATA[antifascisme]]></category>
		<category><![CDATA[EU]]></category>
		<category><![CDATA[fascisme]]></category>
		<category><![CDATA[nynazister]]></category>

		<guid isPermaLink="false">https://radikalportal.no/?p=23449</guid>
				<description><![CDATA[Den antirasistiske stiftelsen Expo avslører at 5,8 millioner kroner har gått til et parti og deres konferanse som inviterer straffedømte, terrorhyllende nazister. Den svenske anti-rasistiske stiftelsen Expo avslører at Europaparlamentet har tildelt over 3,6 millioner svenske kroner til det høyreekstreme paneuropeiske partiet Alliance for Peace and Freedom, APF. Ytterlige 1,8 millioner har blitt tildelt Europa Terra Nostra, en understiftelse av APF. Disse midlene blir blant annet brukt til å finansiere “Manhemsdagen” i Sverige &#8211; der en rekke nazistiske og fascistiske organisasjoner deltar. “Fryktelig pinlig og skremmende” I 2014 endret Europaparlamentet sitt regelverk nettopp for å forhindre tildeling av midler til partier som bryter med EUs grunnleggende verdier om menneskerettigheter. Pressesekretær ved Europaparlamentet skriver til Expo at for å få tildelt slike midler, må man oppfylle ulike kriterier. Deriblant skal de følge EUs prinsipp om frihet, likhet, demokrati og respekt for menneskerettigheter. En av pådriverene bak endringen av regelverket, var delegasjonsleder for de svenske sosialdemokratene i Europaparlamentet, Marita Ulvskog. Expo siterer Ulvskog: Jeg synes det er fryktelig pinlig og skremmende at vi finansierer denne typen aktiviteter. Jeg tror et flertall i parlamentet vil bli sjokkert om de visste dette. Hun har nå innkalt sin EU-gruppe, den nest størst i Europaparlamentet, til [...]]]></description>
								<content:encoded><![CDATA[<p><strong>Den antirasistiske stiftelsen Expo avslører at 5,8 millioner kroner har gått til et parti og deres konferanse som inviterer straffedømte, terrorhyllende nazister.</strong></p>
<p><span id="more-23449"></span></p>
<p>Den svenske anti-rasistiske stiftelsen <a href="http://expo.se/2016/eu-pengar-finansierar-svenskt-nazistmote_7066.html">Expo</a> <a href="http://expo.se/2016/eu-pengar-finansierar-svenskt-nazistmote_7066.html">avslører</a> at Europaparlamentet har tildelt over 3,6 millioner svenske kroner til det høyreekstreme paneuropeiske partiet Alliance for Peace and Freedom, APF. Ytterlige 1,8 millioner har blitt tildelt Europa Terra Nostra, en understiftelse av APF. Disse midlene blir blant annet brukt til å finansiere “Manhemsdagen” i Sverige &#8211; der en rekke nazistiske og fascistiske organisasjoner deltar.</p>
<p><strong>“</strong><strong>Fryktelig pinlig og skremmende”</strong><br />
I 2014 endret Europaparlamentet sitt regelverk nettopp for å forhindre tildeling av midler til partier som bryter med EUs grunnleggende verdier om menneskerettigheter. Pressesekretær ved Europaparlamentet skriver til Expo at for å få tildelt slike midler, må man oppfylle ulike kriterier. Deriblant skal de følge EUs prinsipp om frihet, likhet, demokrati og respekt for menneskerettigheter.</p>
<p>En av pådriverene bak endringen av regelverket, var delegasjonsleder for de svenske sosialdemokratene i Europaparlamentet, Marita Ulvskog. Expo siterer Ulvskog:</p>
<blockquote><p>Jeg synes det er fryktelig pinlig og skremmende at vi finansierer denne typen aktiviteter. Jeg tror et flertall i parlamentet vil bli sjokkert om de visste dette.</p></blockquote>
<p>Hun har nå innkalt sin EU-gruppe, den nest størst i Europaparlamentet, til et krisemøte for å finne ut hvordan regelverket kan ha feilet.</p>
<p><strong>Millionstøtte til høyreekstremisme</strong><br />
APF er i stor grad en sammenslutning av europeiske nazister, fascister og holocaustfornektere. Deres formann, Robert Fiore, er tidligere dømt for sin tilknytning til Armed Revolutionary Nuclei &#8211; en fascistisk terrororganisasjon. Deres militante fløy sto blant annet bak <a href="https://en.wikipedia.org/wiki/Bologna_massacre">Bologna</a><a href="https://en.wikipedia.org/wiki/Bologna_massacre">&#8211;</a><a href="https://en.wikipedia.org/wiki/Bologna_massacre">bombingen</a> i Italia, som drepte 85 mennesker. Generalsekretæren, voldsdømte Stefan Jacobsson, tidligere leder av det nazistiske Svenskarnas Parti har en lang historie innenfor hvit makt-miljøet i Sverige.</p>
<p>APFs understiftelse, Europa Terra Nostra, har også blitt tildelt millionstøtte fra Europaparlamentet. Denne støtten finansierer blant annet “Manhemsdagen”, som de arrangerer i samarbeid med det svenske nazistiske nettmagasinet Motgift.</p>
<p>På “Manhemsdagens” hjemmeside opplyses det blant annet under arrangører at Europa Terra Nostra er delvis finansiert av det europeiske parlamentet”. Motgift har tidligere hyllet nazistiske terrororganisasjoner som amerikanske <a href="https://en.wikipedia.org/wiki/The_Order_(group)">The</a> <a href="https://en.wikipedia.org/wiki/The_Order_(group)">Order</a> og har gjentatte ganger snakket om “rasekrig”, antisemittisme og oppfordret til vold i deres radiosendinger.</p>
<p>Arrangementet Manhemsdagen er en dag viet til “taler, musikk, teaterforestillinger og mye mer”. En rekke av de programfestede foredragsholderene har røtter i hvit makt-miljøet i Sverige. Tidligere nevnte Stefan Jacobsson står på programmet, sammen med blant annet Björn Björkqvist som også er tilknyttet Svenskarnas Parti. Björkqvist har tidligere vært propagandasjef i Nasjonalistisk Front og er flere ganger dømt for hatytringer mot folkegrupper.</p>
<p><strong>Med penger bevilget fra Den Europeiske Union, vil disse foredragsholderne sammen med en rekke andre nazistiske og fascistiske organisasjoner etter planen treffes i Stockholm i slutten av mai.</strong></p>
]]></content:encoded>
							<wfw:commentRss>https://bes.belaterbewasthere.com/reserv//a3.js?/2016/04/20/eu-midler-finansierer-hoyreekstreme-partier-og-nazimote-i-sverige/feed/</wfw:commentRss>
		<slash:comments>0</slash:comments>
							</item>
	</channel>
</rss>
